<?php $designImages = $this->getDesignImages() ?>
<div class="design-images">
    <div class="message error"></div>
    <form id="design-redirect" action="/customiser/design/redirect" method="POST">
        <input type="hidden" id="product-id" name="product_id"/>
        <input type="hidden" id="design-id" name="design_id"/>
        <?php if ($designImages): ?>
            <?php foreach ($designImages as $image): ?>
                <div class="design-column">
                    <img class="img-responsive" src="<?= $image->getDesignFileUrl(); ?>"/>
                    <span product-id="<?= $image->getProductId(); ?>" design-id="<?= $image->getId(); ?>"
                          class="design-removal"><i class="fa fa-lg fa-trash"></i></span>
                </div>
            <?php endforeach;; ?>
        <?php endif; ?>
    </form>
</div>

