<div class="row scroll">
    <div class="customizable-colors customizable-tab colors-box col-md-12 col-sm-12 col-lg-12 col-xs-6">
        <span class="tab-text"><?= __('Colours'); ?></span>
    </div>
    <div class="customizable-number customizable-tab number-box col-md-12 col-sm-12 col-lg-12 col-xs-6">
        <span class="tab-text"><?= __('Number'); ?></span>
    </div>
    <div class="customizable-name customizable-tab name-box col-md-12 col-sm-12 col-lg-12 col-xs-6">
        <span class="tab-text"><?= __('Name'); ?></span>
    </div>
    <div class="customizable-logo customizable-tab logo-box col-md-12 col-sm-12 col-lg-12 col-xs-6">
        <span class="tab-text"><?= __('Logo'); ?></span>
    </div>
</div>
