<?php

$data = file_get_contents('https://api.feefo.com/api/10/reviews/all?merchant_identifier=kartdavid-ltd&page_size=3');

$data = json_decode($data,true);


?>
<script type="text/javascript">

require([ 'jquery'], function($){ 
	$(document).ready(function($) {
		var rcount = '<?php echo $data['summary']['meta']['count'] ; ?>';
		$(".srating").text(' '+rcount);
	});
});
</script>
<style>
.srating{color:#fff !important;}
.checked{color:#fffc16;}
.review{
	width: 33.33%;
    float: left;
	padding:20px;
	min-height:215px;
}
.col-lg-6{ width:50%;float:left;}
.reivew_html{
	width:100%;
	float:left;
	background: #e4002b;
    margin-bottom: 15px;
	padding-bottom: 25px;
}
.rdate{text-align:right;font-size:15px;color:#fff;font-weight:600}
.review_content{
	padding-top: 10px;
    float: left;
    padding-bottom: 10px;
	color:#fff;
	font-size:20px;
}
.review_footer{font-size:15px;font-weight:600;color:#fff;font-style:italic;}
.reivew_html h2{text-align:center;color:#fff;}
.review:nth-child(3), .review:nth-child(2){border-right: 1px solid #fff;}
.review_button{float:left;width:100%;text-align:center;    margin-top: 20px;}
.review_button a{
	padding:10px;
	background:red;
	color:#fff;
	cursor: pointer;
    font-size: 20px;
    border-radius: 5px;
	text-decoration:none;
}
</style>
<div class="reivew_html">
	<h2>Reviews</h2>
	<?php foreach($data['reviews'] as $k=>$v){	?>
	<div class="review">
		<div class="review_top">
			<div class="col-lg-6">
				<?php for($i=0; $i < 5; $i++){
						if($i < $v['service']['rating']['rating']){
						?>
						<span class="fa fa-star checked"></span>
					<?php }else{
						?>
						<span class="fa fa-star"></span>
						<?php
						}
				}?>
				
			</div>
			<div class="col-lg-6 rdate">
				<?php echo date("jS, M Y", strtotime($v['service']['created_at'])); ?>
			</div>
		</div>
		<div class="review_content">
			<?php echo $v['service']['review']; ?>
		</div>
		<div class="review_footer">
			<div class="col-lg-6"><?php if(isset($v['customer'])){
				echo $v['customer']['display_name']; 
			}
			?></div>
		</div>
	</div>
	<?php } ?>
	<div class="review_button"><a href="<?php echo $this->getBaseUrl(); ?>reviews/" class="more_reviews">More Reviews</a></div>
</div>