<form id="custom-form" class="form" action="<?php echo $this->getUrl('freesample/index/save'); ?>" method="post" data-mage-init="{&quot;validation&quot;: {}}">
<div class="form-group field required"><label for="name">Name:</label> <input id="name" class="form-control" name="name" type="text" placeholder="Enter your name" data-validate="{required:true}"></div>
<div class="form-group field required"><label for="input_email">Email:</label> <input id="input_email" class="form-control" name="email" type="email" placeholder="Enter your email address" data-validate="{required:true, 'validate-email':true}"></div>
<div class="form-group field required"><label for="street">Street:</label> <input id="street" class="form-control" name="street" type="text" placeholder="Enter your street" data-validate="{required:true}"></div>
<div class="form-group field required"><label for="city">City</label> <input id="city" class="form-control" name="city" type="text" placeholder="Enter your city" data-validate="{required:true}"></div>
<div class="form-group field required"><label for="post_code">Postal Code:</label> <input id="post_code" class="form-control" name="postal_code" type="text" placeholder="Enter your postal code" data-validate="{required:true}"></div>
<div class="form-group field required"><label for="country">Country</label> <input id="country" class="form-control" name="country" type="text" placeholder="Enter your country" data-validate="{required:true}"></div>
<button id="form-btn" class="btn btn-primary" disabled="disabled" type="submit">Send me samples</button></form>
<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
 
  var dataForm = $('#custom-form');
  dataForm.mage('validation', {});
  $("#name,#input_email,#street,#city,#post_code,#country").on("keyup", function(){
      if($(this).val() != "" && $("#input_email").val() != "" && $("#street").val() != "" && $("#city").val() != "" && $("#post_code").val() != "" &&  $("#country").val() != "" ){
          $("#form-btn").removeAttr("disabled");
      }
   else{
          $("#form-btn").attr("disabled",true);
      }
  });
});
</script>