<?php
/* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Select */
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>
<div class="field<?php echo $class ?> container">
    <div class="options row">
        <div class="col-md-12">
            <label class="label customizable-product-label" for="select_<?php echo $_option->getId() ?>">
                <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span><span class="required">*</span>
            </label>
        </div>
        <div class="col-md-8 col-xs-9">
            <div class="control bodywork-select" data-layer-id="<?= $_option->getLayerId();?>" id="<?= $_option->getTitle() == 'CustomizationPrice' ? 'customization-price-checkbox' : '' ?>">
                <?php echo $block->getValuesHtml() ?>
                <?php if ($_option->getIsRequire()): ?>
                    <?php if ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_RADIO || $_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_CHECKBOX): ?>
                        <span id="options-<?php echo $_option->getId() ?>-container"></span>
                    <?php endif; ?>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>
