<?php
/** @var \Magento\Sales\Block\Adminhtml\Order\View\Items $block */
$i = 0;
$columns = $block->getColumns();
$lastItemNumber = count($columns);
?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
        <tr class="headings">
            <?php foreach ($columns as $columnName => $columnTitle): $i++; ?>
                <th class="col-<?php echo $columnName ?><?php echo ($i === $lastItemNumber ? ' last' : '') ?>"><span><?php echo $columnTitle ?></span></th>
            <?php endforeach; ?>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <?php $_items = $block->getItemsCollection();?>
        <?php foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()): ?>
                <?php continue; ?>
            <?php else: ?>
                <?php $i++; ?>
            <?php endif; ?>
            <tbody class="<?php echo $i%2 ? 'even' : 'odd' ?>">
                <?php echo $block->getItemHtml($_item) ?>
                <?php echo $block->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
