<?php
/** @var Bison\CustomizableProducts\Block\Customizer\Inputs $block */
$logos = $block->getProductLogosCategory();
?>
<div class="logos">
        <div class="images">
            <?php foreach($logos as $logo):?>
                <div class="logo-container">
                    <span class="label"><?php echo $block->escapeHtml($logo['name']);?></span>
                    <div class="img-container">
                        <img src="<?php echo $block->escapeUrl($logo['url']);?>"
                             class="logo-image"
                             data-id="-<?php echo $block->escapeHtml($logo['id']);?>"
                             data-width="<?php echo $block->escapeHtml($logo['width']);?>"
                             data-height="<?php echo $block->escapeHtml($logo['height']);?>"/>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
</div>